let autos = [
  {
    marca: "Ford",
    modelo: "Fiesta",
    km: 200,
    color: "Azul",
    precio: 150000,
    cuotas: 12,
    anio: 2019,
    patente: "APL123",
    vendido: false,
  },
  {
    marca: "Toyota",
    modelo: "Corolla",
    km: 0,
    color: "Blanco",
    precio: 170000,
    cuotas: 14,
    anio: 2019,
    patente: "JJK116",
    vendido: false,
  },
  {
    marca: "Nissan",
    modelo: "Skyline GT-R R34",
    km: 30000,
    color: "Gris",
    precio: 220000,
    cuotas: 18,
    anio: 1999,
    patente: "BNR34",
    vendido: false,
  },
  {
    marca: "Toyota",
    modelo: "Supra",
    km: 5000,
    color: "Naranja",
    precio: 250000,
    cuotas: 24,
    anio: 1994,
    patente: "SUP94",
    vendido: false,
  },
  {
    marca: "Dodge",
    modelo: "Charger",
    km: 15000,
    color: "Negro",
    precio: 300000,
    cuotas: 20,
    anio: 1970,
    patente: "DOM70",
    vendido: false,
  },
];

module.exports = autos;
